name: Rename YouTube Videos

on:
  schedule:
    - cron: '0 1 * * *' # Exécution à 03:00 Europe/Brussels (CET/CEST = UTC+1/2)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib

      - name: Create secrets
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: |
          echo "$CLIENT_SECRET" > client_secrets.json
          echo "$TOKEN_JSON" > token.json

      - name: Run rename script
        run: python script.py
